// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_auth_ from "./routes/api/auth/[...auth].tsx";
import * as $index from "./routes/index.tsx";
import * as $layout_profile from "./islands/layout/profile.tsx";
import * as $layout_search_bar from "./islands/layout/search-bar.tsx";
import * as $layout_search_modal from "./islands/layout/search-modal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/[...auth].tsx": $api_auth_auth_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/layout/profile.tsx": $layout_profile,
    "./islands/layout/search-bar.tsx": $layout_search_bar,
    "./islands/layout/search-modal.tsx": $layout_search_modal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
